# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(934, 426)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 781, 401))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 741, 351))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(810, 40, 111, 141))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.openButton = QtWidgets.QPushButton(self.splitter)
        self.openButton.setObjectName("openButton")
        self.analysisButton = QtWidgets.QPushButton(self.splitter)
        self.analysisButton.setObjectName("analysisButton")
        self.saveButton = QtWidgets.QPushButton(self.splitter)
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数值分析"))
        self.groupBox.setTitle(_translate("Dialog", "响应列表"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "传感器1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "传感器2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "传感器3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "传感器4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "传感器5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "传感器6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "传感器7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "传感器8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "传感器9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "传感器10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "传感器11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "传感器12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "传感器13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "传感器14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "传感器15"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "响应时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "最大值时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "最大值"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "初始稳态值"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "最小值"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "峰值(Max-Min)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "最小值时间"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "响应峰面积"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "恢复峰面积"))
        self.openButton.setText(_translate("Dialog", "Open Data"))
        self.analysisButton.setText(_translate("Dialog", "Analyze"))
        self.saveButton.setText(_translate("Dialog", "Save Data"))

