# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/DekangLogo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.receiveGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.receiveGroup.setGeometry(QtCore.QRect(260, 10, 451, 261))
        self.receiveGroup.setObjectName("receiveGroup")
        self.receiveText = QtWidgets.QTextBrowser(self.receiveGroup)
        self.receiveText.setGeometry(QtCore.QRect(10, 20, 431, 231))
        self.receiveText.setObjectName("receiveText")
        self.settingGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.settingGroup.setGeometry(QtCore.QRect(20, 10, 221, 261))
        self.settingGroup.setObjectName("settingGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.settingGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 181, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.reButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reButton.setObjectName("reButton")
        self.gridLayout.addWidget(self.reButton, 14, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.gridLayoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.readnumLab = QtWidgets.QLabel(self.splitter)
        self.readnumLab.setObjectName("readnumLab")
        self.readnumBox = QtWidgets.QComboBox(self.splitter)
        self.readnumBox.setObjectName("readnumBox")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.readnumBox.addItem("")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 2, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 7, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(720, 30, 51, 31))
        self.clearButton.setObjectName("clearButton")
        self.logoLab = QtWidgets.QLabel(self.centralwidget)
        self.logoLab.setGeometry(QtCore.QRect(260, 320, 471, 71))
        self.logoLab.setStyleSheet("image: url(:/icons/images/HSUTDekang.png);")
        self.logoLab.setText("")
        self.logoLab.setObjectName("logoLab")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 280, 221, 101))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 201, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stateLab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.stateLab.setObjectName("stateLab")
        self.gridLayout_2.addWidget(self.stateLab, 1, 0, 1, 1)
        self.recordLab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.recordLab.setObjectName("recordLab")
        self.gridLayout_2.addWidget(self.recordLab, 0, 0, 1, 1)
        self.recordEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.recordEdit.setCursorPosition(1)
        self.recordEdit.setReadOnly(True)
        self.recordEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.recordEdit.setObjectName("recordEdit")
        self.gridLayout_2.addWidget(self.recordEdit, 0, 1, 1, 1)
        self.stateEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.stateEdit.setReadOnly(True)
        self.stateEdit.setObjectName("stateEdit")
        self.gridLayout_2.addWidget(self.stateEdit, 1, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(720, 80, 51, 31))
        self.saveButton.setObjectName("saveButton")
        self.drawBox = QtWidgets.QCheckBox(self.centralwidget)
        self.drawBox.setGeometry(QtCore.QRect(260, 280, 211, 16))
        self.drawBox.setObjectName("drawBox")
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(720, 130, 51, 31))
        self.drawButton.setObjectName("drawButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -2, 801, 421))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image: url(:/icons/images/backImg1.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.receiveGroup.raise_()
        self.settingGroup.raise_()
        self.clearButton.raise_()
        self.logoLab.raise_()
        self.groupBox.raise_()
        self.saveButton.raise_()
        self.drawBox.raise_()
        self.drawButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 17))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actSer = QtWidgets.QAction(MainWindow)
        self.actSer.setObjectName("actSer")
        self.actAboutSys = QtWidgets.QAction(MainWindow)
        self.actAboutSys.setObjectName("actAboutSys")
        self.actAboutQt = QtWidgets.QAction(MainWindow)
        self.actAboutQt.setObjectName("actAboutQt")
        self.actAnalyze = QtWidgets.QAction(MainWindow)
        self.actAnalyze.setObjectName("actAnalyze")
        self.menu.addAction(self.actAboutSys)
        self.menu.addAction(self.actAboutQt)
        self.menu_2.addAction(self.actSer)
        self.menu_2.addAction(self.actAnalyze)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.readnumBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "得康科技气体管理系统"))
        self.receiveGroup.setTitle(_translate("MainWindow", "Receive"))
        self.settingGroup.setTitle(_translate("MainWindow", "Setting"))
        self.reButton.setText(_translate("MainWindow", "重置"))
        self.readnumLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">读取次数:</span></p></body></html>"))
        self.readnumBox.setCurrentText(_translate("MainWindow", "10"))
        self.readnumBox.setItemText(0, _translate("MainWindow", "1"))
        self.readnumBox.setItemText(1, _translate("MainWindow", "5"))
        self.readnumBox.setItemText(2, _translate("MainWindow", "10"))
        self.readnumBox.setItemText(3, _translate("MainWindow", "20"))
        self.readnumBox.setItemText(4, _translate("MainWindow", "50"))
        self.readnumBox.setItemText(5, _translate("MainWindow", "100"))
        self.readnumBox.setItemText(6, _translate("MainWindow", "150"))
        self.readnumBox.setItemText(7, _translate("MainWindow", "200"))
        self.readnumBox.setItemText(8, _translate("MainWindow", "500"))
        self.readnumBox.setItemText(9, _translate("MainWindow", "1000"))
        self.readnumBox.setItemText(10, _translate("MainWindow", "2000"))
        self.openButton.setText(_translate("MainWindow", "开启串口"))
        self.stopButton.setText(_translate("MainWindow", "关闭串口"))
        self.startButton.setText(_translate("MainWindow", "开始录入"))
        self.clearButton.setText(_translate("MainWindow", "清除"))
        self.groupBox.setTitle(_translate("MainWindow", "State"))
        self.stateLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">串口状态:</span></p></body></html>"))
        self.recordLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">录入次数:</span></p></body></html>"))
        self.recordEdit.setText(_translate("MainWindow", "0"))
        self.stateEdit.setText(_translate("MainWindow", "已搜索到串口"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.drawBox.setText(_translate("MainWindow", "录入完毕后绘制图像"))
        self.drawButton.setText(_translate("MainWindow", "绘图"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.actSer.setText(_translate("MainWindow", "串口设置"))
        self.actSer.setToolTip(_translate("MainWindow", "串口设置"))
        self.actAboutSys.setText(_translate("MainWindow", "关于系统"))
        self.actAboutSys.setToolTip(_translate("MainWindow", "关于系统"))
        self.actAboutQt.setText(_translate("MainWindow", "关于Qt"))
        self.actAboutQt.setToolTip(_translate("MainWindow", "关于Qt"))
        self.actAnalyze.setText(_translate("MainWindow", "数据分析"))
        self.actAnalyze.setToolTip(_translate("MainWindow", "数据分析"))

import res_rc
