# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(241, 205)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(73, 160, 77, 31))
        self.btnOK.setObjectName("btnOK")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 171, 115))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.baudBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.baudBox.setObjectName("baudBox")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.gridLayout.addWidget(self.baudBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.stopBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.stopBox.setObjectName("stopBox")
        self.stopBox.addItem("")
        self.stopBox.addItem("")
        self.stopBox.addItem("")
        self.gridLayout.addWidget(self.stopBox, 4, 1, 1, 1)
        self.byteBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.byteBox.setObjectName("byteBox")
        self.byteBox.addItem("")
        self.byteBox.addItem("")
        self.byteBox.addItem("")
        self.byteBox.addItem("")
        self.gridLayout.addWidget(self.byteBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.serBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.serBox.setObjectName("serBox")
        self.gridLayout.addWidget(self.serBox, 5, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(153, 160, 77, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.serLab = QtWidgets.QLabel(Dialog)
        self.serLab.setGeometry(QtCore.QRect(20, 130, 171, 21))
        self.serLab.setObjectName("serLab")

        self.retranslateUi(Dialog)
        self.baudBox.setCurrentIndex(6)
        self.byteBox.setCurrentIndex(3)
        self.btnOK.clicked.connect(Dialog.accept)
        self.btnCancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnOK.setText(_translate("Dialog", "确认"))
        self.baudBox.setCurrentText(_translate("Dialog", "9600"))
        self.baudBox.setItemText(0, _translate("Dialog", "110"))
        self.baudBox.setItemText(1, _translate("Dialog", "300"))
        self.baudBox.setItemText(2, _translate("Dialog", "600"))
        self.baudBox.setItemText(3, _translate("Dialog", "1200"))
        self.baudBox.setItemText(4, _translate("Dialog", "2400"))
        self.baudBox.setItemText(5, _translate("Dialog", "4800"))
        self.baudBox.setItemText(6, _translate("Dialog", "9600"))
        self.baudBox.setItemText(7, _translate("Dialog", "14400"))
        self.baudBox.setItemText(8, _translate("Dialog", "19200"))
        self.baudBox.setItemText(9, _translate("Dialog", "38400"))
        self.baudBox.setItemText(10, _translate("Dialog", "56000"))
        self.baudBox.setItemText(11, _translate("Dialog", "57600"))
        self.baudBox.setItemText(12, _translate("Dialog", "115200"))
        self.baudBox.setItemText(13, _translate("Dialog", "128000"))
        self.baudBox.setItemText(14, _translate("Dialog", "256000"))
        self.label_2.setText(_translate("Dialog", "波特率"))
        self.stopBox.setItemText(0, _translate("Dialog", "1"))
        self.stopBox.setItemText(1, _translate("Dialog", "1.5"))
        self.stopBox.setItemText(2, _translate("Dialog", "2"))
        self.byteBox.setItemText(0, _translate("Dialog", "5"))
        self.byteBox.setItemText(1, _translate("Dialog", "6"))
        self.byteBox.setItemText(2, _translate("Dialog", "7"))
        self.byteBox.setItemText(3, _translate("Dialog", "8"))
        self.label_3.setText(_translate("Dialog", "数据位"))
        self.label_4.setText(_translate("Dialog", "停止位"))
        self.label.setText(_translate("Dialog", "串口号"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.serLab.setText(_translate("Dialog", "未搜索到串口"))

