# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(956, 456)
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 781, 401))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 741, 351))
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.splitter = QtWidgets.QSplitter(Widget)
        self.splitter.setGeometry(QtCore.QRect(820, 50, 111, 141))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "数值检测"))
        self.groupBox.setTitle(_translate("Widget", "响应列表"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Widget", "传感器1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Widget", "传感器2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Widget", "传感器3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Widget", "传感器4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Widget", "传感器5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Widget", "传感器6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Widget", "传感器7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Widget", "传感器8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Widget", "传感器9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Widget", "传感器10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Widget", "传感器11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Widget", "传感器12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Widget", "传感器13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Widget", "传感器14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Widget", "传感器15"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "响应时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "峰值时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "峰值"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "最大正斜率"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "最大负斜率"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Widget", "稳态值"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Widget", "恢复时间"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Widget", "响应峰面积"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Widget", "恢复峰面积"))
        self.pushButton.setText(_translate("Widget", "Open Data"))
        self.pushButton_2.setText(_translate("Widget", "Analyze"))
        self.pushButton_3.setText(_translate("Widget", "Save Data"))

